### ISSUE TITLE
Clean up for Milestone Alpha 1

### ISSUE THREAD

**Issue by thedocruby** [thedocruby/resounding#13]
Clean up code before releasing Milestone Alpha 1.

- [x] #9
- [x] #2
- [x] Lang for new features
- [x] Tidy comments and TODOs
- [x] Tidy annotations
- [x] Tidy imports
- [x] Tidy whitespace
- [x] Optimize where possible.
